### ISSUE TITLE
Add left and right margin to .main element

### ISSUE THREAD

**Issue by ricofreak** [jajm/koha-staff-interface-redesign#57]
Almost every page contains the element:

```html
<div class="main container-fluid">
```

There is no left or right padding and content sits flush up against the page. It would be nice if there was a little bit of margin here:

```css
.main {
    margin-right: 15px;
    margin-left: 15px;
}
```

That way there is a little bit of separation between content and the side of each page.
